use-sort:
    group:
        - _main
        - Octante
    group-type: each
    sort-type: alph
    sort-direction: asc

header: |
    /*
     * This file is part of the OctanteMarvelAPI package.
     *
     * (c) Issel Guberna <issel.guberna@gmail.com>
     *
     * For the full copyright and license information, please view the LICENSE
     * file that was distributed with this source code.
     */