language: php

php:
   - 5.4
   - 5.5
   - 5.6
   - hhvm

install:
  - composer require satooshi/php-coveralls:~0.6@stable

before_script:
   - mkdir -p build/logs
   - composer install --no-interaction --dev

script:
   - phpunit -c phpunit.xml.dist --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'