language: php

php:
   - 5.4
   - 5.5
   - 5.6
   - hhvm

before_script:
   - composer install --no-interaction --dev

install:
  - composer require satooshi/php-coveralls:~0.6@stable

script:
   - phpunit -c phpunit.xml.dist --coverage-text